name: Standalone CLI
on: [push, pull_request]
jobs:
   machineStandalone:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: docker://docker.io/fluidattacks/cli:latest
           name: Run FluidAttacks CLI
           id: scan
           with:
              args: skims scan .
         - name: Check scan result
           run: |
              if [ -f ./result.log ]; then
                 cat ./result.log
                 exit 1
              fi
           shell: bash


